services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminadmin
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - "27017:27017"
    networks:
      - networkclienter2

  mysql-pos:
    image: mysql:8.4.5-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_DATABASE: noa_pos
      MYSQL_USER: posnoa
      MYSQL_PASSWORD: adminadmin
    ports:
      - 3307:3306
    volumes:
      - type: bind
        source: ./data-mysql
        target: /var/lib/mysql
    networks:
      - networkclienter2

  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - networkclienter2

  appweb-posnoa:
    image: com.noa/app-web-posnoa:1.0.0
    depends_on:
      - redis
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
                      "spring.datasource.url"  : "jdbc:mysql://mysql-pos:3306/noa_pos",
                      "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
                      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
                      "spring.jpa.hibernate.ddl-auto" : "update",
                      "spring.datasource.username" : "posnoa",
                      "spring.datasource.password" : "adminadmin",
                      "spring.security.matcher" : "/;/home/login",
                      "app.upload.images.path" : "/app/"
                      }'
      SPRING_DATA_REDIS_HOST: "redis"
    networks:
      - networkclienter2

networks:
  networkclienter2: